<?php
// Start output buffering
ob_start(); 

include '../../controllers/ContractController.php';
require_once('../../vendor/tecnickcom/tcpdf/tcpdf.php'); // Corrected path to TCPDF

$contractController = new ContractController();
$contractId = $_GET['id'] ?? 0;

// Fetch contract, user, and car details
$contract = $contractController->getContractById($contractId);
$user = $contractController->getUserById($contract['user_id']);
$car = $contractController->getCarById($contract['car_id']);

if (!$contract || !$user || !$car) {
    die("Contract, User, or Car not found.");
}

// Create new PDF document
$pdf = new TCPDF();
$pdf->AddPage();

// Set title font
$pdf->SetFont('helvetica', 'B', 20);
$pdf->Cell(0, 10, 'Contract Details', 0, 1, 'C');
$pdf->Ln(10); // Add space

// Add contract details with borders
$pdf->SetFillColor(220, 220, 220); // Light gray background for header
$pdf->SetFont('helvetica', 'B', 12);
$pdf->Cell(0, 10, 'Contract Information', 1, 1, 'C', 1); // Header with border

$pdf->SetFont('helvetica', '', 12);
$pdf->Cell(0, 10, 'Contract ID: ' . $contract['id'], 1, 1);
$pdf->Cell(0, 10, 'Start Date: ' . $contract['start_date'], 1, 1);
$pdf->Cell(0, 10, 'End Date: ' . $contract['end_date'], 1, 1);
$pdf->Cell(0, 10, 'Total Payment: ' . $contract['total_payment'] . ' MAD', 1, 1);
$pdf->Ln(5); // Add space

// Add user details
$pdf->SetFillColor(220, 220, 220); // Light gray background for header
$pdf->SetFont('helvetica', 'B', 12);
$pdf->Cell(0, 10, 'User Details:', 1, 1, 'C', 1); // Header with border

$pdf->SetFont('helvetica', '', 12);
$pdf->Cell(0, 10, 'Name: ' . $user['prenom'] . ' ' . $user['nom'], 1, 1);
$pdf->Cell(0, 10, 'Email: ' . $user['email'], 1, 1);
$pdf->Ln(5); // Add space

// Add car details
$pdf->SetFillColor(220, 220, 220); // Light gray background for header
$pdf->SetFont('helvetica', 'B', 12);
$pdf->Cell(0, 10, 'Car Details:', 1, 1, 'C', 1); // Header with border

$pdf->SetFont('helvetica', '', 12);
$pdf->Cell(0, 10, 'Vehicle Title: ' . $car['vehicletitle'], 1, 1);
$pdf->Cell(0, 10, 'Matricule: ' . $car['matricule'], 1, 1);
$pdf->Cell(0, 10, 'Price per Day: ' . $car['price_per_day'] . ' TND', 1, 1);
$pdf->Cell(0, 10, 'Fuel Type: ' . $car['fuel_type'], 1, 1);
$pdf->Ln(10); // Add space

// Add a footer with some additional information
$pdf->SetY(-30); // Position at 30 mm from bottom
$pdf->SetFont('helvetica', 'I', 8);
$pdf->Cell(0, 10, 'This document is generated by Our Car Rental System', 0, 0, 'C');

// Clear the output buffer
ob_end_clean(); 

// Output PDF
$pdf->Output('contract_' . $contract['id'] . '.pdf', 'D');
?>
